# Change these first
owner: rcmdnk # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: rcmdnk' blog
    url: https://rcmdnk.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: rcmdnk.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: rcmdnk.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status of rcmdnk's blog, powered by [Upptime](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
